name = "fortfound_app"
version = "1.0.0"
description = "Clean room reimplementation of Zachtronics' Fortune's Foundation solitaire game."
target = "javascript"
licences = ["AGPL-3.0-or-later"]
repository = { type = "github", user = "jcloward13", repo = "fortfound" }
links = [{ title = "Home page", href = "https://jcloward13.github.io/fortfound" }]
dev-dependencies = { lustre_dev_tools = ">= 1.7.0 and < 2.0.0" }

[dependencies]
gleam_stdlib = ">= 0.56.0 and < 1.0.0"
lustre = { git = "https://github.com/lustre-labs/lustre", ref = "4.6.4" }
modem = ">= 2.0.1 and < 3.0.0"
fortfound_core = { path = "../fortfound_core" }
glector = ">= 1.1.0 and < 2.0.0"
lustre_animation = { git = "https://github.com/jcloward13/lustre_animation", ref = "main" }
